### ISSUE TITLE
Support for no transition

### ISSUE THREAD

**Issue by Artucuno** [denchiklut/loadable-image#16]
Hey there,

Can you please add support for having no transition?

Thanks,
Artu

**Comment by denchiklut** [comment]
@Artucuno can you please explain a bit more your use case? 
There is a prop `Transition` you can pass any custom transition in your case it can be a Fade with duration time 0,

You can also adjust the `rootMargin` to ensure that images load and begin their transition before they appear on the screen. This property sets a margin around the root element, determining when to `initiate` an image `download`.

**Comment by denchiklut** [comment]
Resolved in  latest release: `v3.2.5`
You will now be able to pass `timeout` prop which sets the duration for the transition, in milliseconds.
