### ISSUE TITLE
Console Error after Adding Package

### ISSUE THREAD

**Issue by TotalSimplicity** [denchiklut/loadable-image#19]
Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?

Check the render method of `Transition2`.

**Comment by denchiklut** [comment]
Hey @TotalSimplicity can you provide link to a code snippet. Or add some details about your case 🙏🏻
But based on the error you provided I think you probably forgot to use [forwardRef](https://react.dev/reference/react/forwardRef#forwardref)
Things that can help: package version, react version and props that you pass to the AsyncImage component.

**Comment by denchiklut** [comment]
Closing this for now
