### ISSUE TITLE
Framer motion tag support

### ISSUE THREAD

**Issue by OSAMA263** [denchiklut/loadable-image#22]
can i use framer motion with AsyncImage ?
like be able to use motion.img with it?

**Comment by denchiklut** [comment]
> can i use framer motion with AsyncImage ?
> 
> like be able to use motion.img with it?

I'm not sure about this. The thing is. This library already utilizes [react-transition-group](https://github.com/reactjs/react-transition-group) (it's a small animation library maintained by react team)
