### ISSUE TITLE
wrapping in div / link

### ISSUE THREAD

**Issue by ariyin** [denchiklut/loadable-image#23]
hello! when i wrap an `AsyncImage` with a `div` or a `Link`, the image never renders. i'm not sure if i'm doing anything wrong and would appreciate some input on this:

(left the ... as placeholder for the settings used)

```
<Link to={link} target="_blank" rel="noopener noreferrer">
     <AsyncImage ... />
</Link>
```
```
<div>
     <AsyncImage ... />
</div>
```

so far, i've found a workaround for the link (which is using an onClick function to open a page) but can't really think of a workaround for the div since i want to position something relative to the image (ex: positioning tags on the lower left corner of the image). any help would be appreciated!

**Comment by ariyin** [comment]
i think there was a bug where i needed to set `width=100%` on the outer div styling the `AsyncImage` otherwise the image would shrink and appear as if it didn't exist. not sure why, but i managed to fix it. 

this was my original code:

```
<div className="image-tag">
     <AsyncImage ... />
     <div className="skill">
          {skills.map((skill, index) => (
            <Chip key={index} label={skill} />
          ))}
     </div>
</div>
```
```
.image-tag {
  display: flex;
  flex-direction: column;
  position: relative;
  transform: scale(0.9);
}
```

and the fixed css:

```
.image-tag {
  display: flex;
  flex-direction: column;
  position: relative;
  transform: scale(0.9);
  width: 100%;
}
```

when i was testing the `Link`, i wrapped it around the `AsyncImage` while in the div that didn't have `width=100%`. 

(so like this)

```
<div className="image-tag">
  <Link>
     <AsyncImage ... />
  </Link>
  <div className="skill">
          {skills.map((skill, index) => (
            <Chip key={index} label={skill} />
          ))}
  </div>
</div>
```

so in the end the only issue was the outer div.

**Comment by denchiklut** [comment]
> hello! when i wrap an `AsyncImage` with a `div` or a `Link`, the image never renders. i'm not sure if i'm doing anything wrong and would appreciate some input on this:
> 
> 
> 
> (left the ... as placeholder for the settings used)
> 
> 
> 
> ```
> 
> <Link to={link} target="_blank" rel="noopener noreferrer">
> 
>      <AsyncImage ... />
> 
> </Link>
> 
> ```
> 
> ```
> 
> <div>
> 
>      <AsyncImage ... />
> 
> </div>
> 
> ```
> 
> 
> 
> so far, i've found a workaround for the link (which is using an onClick function to open a page) but can't really think of a workaround for the div since i want to position something relative to the image (ex: positioning tags on the lower left corner of the image). any help would be appreciated! 

Yes your are right. U do need to specify either width & height or the aspectRation (u can use both css className or style prop for that (just as it's done in examples)
