### ISSUE TITLE
Tailwind Support

### ISSUE THREAD

**Issue by LFSCamargo** [denchiklut/loadable-image#7]
Is there a way to use this with Tailwind CSS without passing the style property?

**Comment by denchiklut** [comment]
> Is there a way to use this with Tailwind CSS without passing the style property?

@LFSCamargo you should be able to pass `className` as a prop. But yeah you still need to pass both `width & height` as a style prop.

**Comment by too-soon** [comment]
`className` is being ommited here, causing Typescript to throw error https://github.com/denchiklut/loadable-image/blob/fcef664909c43a019b08ed7634e7846a15d87045/src/async-image/async-image.types.ts#L21

![image](https://github.com/denchiklut/loadable-image/assets/22935809/0d4b504f-362b-4273-8e17-a8d8bdc46312)

**Comment by denchiklut** [comment]
Added support for the `className` prop. Check out the latest [release: v3.1.1](https://github.com/denchiklut/loadable-image/releases/tag/v3.1.1).
Now, the `style` prop is optional.
Please note that If you don't specify `width & height` or they both have values `auto|100%`, You will need to specify `aspect-ratio` either in your CSS class that you pass as a `className` prop or in the `style` object prop.
